# Generated by Django 6.0.7 on 2026-07-29 08:41

import core.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='同学录名称')),
                ('share_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='分享标识')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebooks', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '同学录',
                'verbose_name_plural': '同学录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_code', models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True, verbose_name='编辑码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='首次提交时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('edit_deadline', models.DateTimeField(blank=True, null=True, verbose_name='编辑截止时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('restore_deadline', models.DateTimeField(blank=True, null=True, verbose_name='还原截止时间')),
                ('name', models.CharField(max_length=50, verbose_name='名字')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
                ('wechat', models.CharField(max_length=50, verbose_name='微信')),
                ('first_impression', models.TextField(verbose_name='对我的第一印象')),
                ('words_to_me', models.TextField(verbose_name='想对我说的话')),
                ('message', models.TextField(verbose_name='留言')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('zodiac_sign', models.CharField(blank=True, max_length=10, null=True, verbose_name='生肖')),
                ('constellation', models.CharField(blank=True, max_length=10, null=True, verbose_name='星座')),
                ('qq', models.CharField(blank=True, max_length=20, null=True, verbose_name='QQ号')),
                ('xiaohongshu', models.CharField(blank=True, max_length=100, null=True, verbose_name='小红书号')),
                ('douyin', models.CharField(blank=True, max_length=100, null=True, verbose_name='抖音号')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('address', models.TextField(blank=True, null=True, verbose_name='地址')),
                ('hobbies', models.TextField(blank=True, null=True, verbose_name='兴趣爱好')),
                ('motto', models.TextField(blank=True, null=True, verbose_name='座右铭')),
                ('crush', models.TextField(blank=True, null=True, verbose_name='喜欢谁')),
                ('dislike', models.TextField(blank=True, null=True, verbose_name='讨厌谁')),
                ('wish', models.TextField(blank=True, null=True, verbose_name='愿望')),
                ('dream', models.TextField(blank=True, null=True, verbose_name='梦想')),
                ('favorite_food', models.TextField(blank=True, null=True, verbose_name='喜欢吃什么')),
                ('most_want_to_see', models.TextField(blank=True, null=True, verbose_name='最想见的人')),
                ('favorite_movie', models.TextField(blank=True, null=True, verbose_name='喜欢看什么电影')),
                ('favorite_music', models.TextField(blank=True, null=True, verbose_name='喜欢听什么歌')),
                ('most_want_to_go', models.TextField(blank=True, null=True, verbose_name='最想去哪')),
                ('most_unforgettable', models.TextField(blank=True, null=True, verbose_name='最难忘的事')),
                ('hope_10_years', models.TextField(blank=True, null=True, verbose_name='希望10年后的我们')),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.notebook', verbose_name='所属同学录')),
            ],
            options={
                'verbose_name': '同学信息',
                'verbose_name_plural': '同学信息',
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.models.student_upload_path, verbose_name='文件')),
                ('file_type', models.CharField(choices=[('photo', '照片'), ('video', '视频')], max_length=10, verbose_name='文件类型')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='文件大小(字节)')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='core.student', verbose_name='所属同学')),
            ],
            options={
                'verbose_name': '媒体文件',
                'verbose_name_plural': '媒体文件',
            },
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('code', models.CharField(max_length=6, verbose_name='验证码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('is_used', models.BooleanField(default=False, verbose_name='是否已使用')),
            ],
            options={
                'verbose_name': '验证码',
                'verbose_name_plural': '验证码',
                'indexes': [models.Index(fields=['email', 'code', 'expires_at'], name='core_verifi_email_e069ff_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['notebook', 'name'], name='core_studen_noteboo_22236f_idx'),
        ),
    ]
