# Generated by Django 6.0.6 on 2026-07-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='title_slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='名称标识'),
        ),
        migrations.AddField(
            model_name='student',
            name='name_slug',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='姓名标识'),
        ),
    ]
